### PR TITLE
Ban some factsheets

### PR DESCRIPTION
**Pull request by radubogdan**
Hello,

Please review my PR for https://github.com/devcenter-square/disease-info/issues/27

I didn't get anything to catch on for deciding if it's a valid disease or not. 

In my opinion it's better to use a dictionary and implement a Factory file that will create records only if the disease it's a "known-one" but meanwhile a method to ban factsheet ids it's enough.

What do you think?

### CODE REVIEW

**Comment by osioke** [comment]
@mykeels You mentioned something?

**Comment by mykeels** [comment]
I mentioned maintaining a list of false positive disease names that the scraper returns so they don't get added to the system.

Another method could be having an "active" property/field on each disease object in the DB. Only diseases with _active_ set to _true_ will be processed by the server and returned as valid diseases.

**Comment by radubogdan** [comment]
Okay @mykeels. It's kind of the same concept isn't it?

Can you provide a list of non-diseases which should I exclude?

**Comment by mykeels** [comment]
Okay @radubogdan 

```
Second global high-level conference on road safety - WHO
Millennium development goals (mdgs) - WHO
Immunization coverage - WHO
```

**Comment by x6iae** [comment]
> Another method could be having an "active" property/field on each disease object in the DB. Only diseases with active set to true will be processed by the server and returned as valid diseases.

I think the above, as mentioned by @mykeels might be the best approach. We can have the scraper get everything, and set active on needed either automatically by the backend, or through some interface that's controllable by admins(this will give more flexibility)

_Pros/Advantages I see with this approach:_
- A disease can easily have it's status changed from active to non-active, and the API will immediately respond to it
- We can then have an endpoint to return list of `"false"` diseases, which can be useful for some other purposes 

_Cons:_
- manual `active` status management

**Comment by radubogdan** [comment]
Great! I'm gonna work on it this weekend 👍

**Comment by osioke** [comment]
@radubogdan @mykeels I also agree with @SundayAdefila, as setting up the interface which will be controllable by admins can also act as a platform for `Verifiers` to verify/control what diseases are being shown or presented.

Nice one @SundayAdefila 

👍 @radubogdan

**Comment by x6iae** [comment]
@radubogdan how is it going on this one please.

**Comment by x6iae** [comment]
Nice work @radubogdan 👍 
I think this is ready as soon as the merge conflict is fixed!

**Comment by radubogdan** [comment]
My fork was out of sync and without a remote and after I fetched I've rebased master into my branch. It's really odd that there is a conflict. I'll fix it.

**Comment by radubogdan** [comment]
Sorry for the delay guys. Let me know if this is what you needed! Thanks @SundayAdefila

**Comment by x6iae** [comment]
Awesome! 

I'll say one more thing that can complete this will be an endpoint to set/unset the `is_active` property, as well as a way to be able to specify to the disease endpoint if it should return either active or in-active diseases.

**Pull request merged**
